export type Language = "en" | "my";

export const defaultLanguage: Language = "en";

export const labels = {
  en: {
    title: "Title",
    name: "Name",
    place: "Place",
    highlights: "Highlights",
    location: "Location",
    date: "Date",
    pinkCard: "Pink Card",
    thai: "Thai Language",
    paymentType: "Payment Type",
    stay: "Stay",
    notes: "Notes",
    adminJobManagement: "Admin Job Management",
    noJobs: "No jobs available",
    backToDashboard: "Back to Dashboard",
    deleteConfirm: "Are you sure you want to delete this post?",
    cancel: "Cancel",
    delete: "Delete",
    add: "Add",
    edit: "Edit",
    address: "Address",
    monthly: "Monthly",
    daily: "Daily",
    addressRequired: "If stay is provided fill this field",
    images: "Images",
    rentFee: "Rent Fee:",
    services: "Services:",
    price: "Price:",
    nearby: "Nearby Places",
    amenities: "Admenities",
    nearbyPlaces: "Nearby Places",
    save: "Save",
    popular: "Popular Picks",
    adminRating: "Ratings",
    rating: "Ratings",
    duration: "Duration",
    coursename: "Name",
    courseprice: "Price",
    centreName: "Centre Name",
    adminJobs: "Admin Jobs",
    adminTravel: "Admin Travel",
    adminCondo: "Admin Condo",
    adminHotels: "Admin Hotels",
    adminDocument: "Admin Documents",
    adminRestaurants: "Admin Restaurants",
    adminCourses: "Admin Courses",
    adminGeneral: "Admin General",
    jobs: "Jobs",
    travel: "Travel",
    condo: "Condo",
    hotels: "Hotels",
    documents: "Documents",
    restaurants: "Restaurants",
    courses: "Courses",
    general: "General",
    socialMediaPrompt: "Join our Social Media Channels & see Updates",
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    footerText: "Whatever you need, YarSu is here",
    loadingJobs: "Loading jobs...",
    bhatNeeded: "Bhat Needed",
    posted: "Posted",
    moreInfo: "More Info",
    apply: "Apply",
    applyForJob: "Apply for Job",
    phoneNumber: "Phone Number",
    birthday: "Birthday",
    thaiLanguage: "Thai Language",
    gender: "Gender",
    yes: "Yes",
    no: "No",
    male: "Male",
    female: "Female",
    selectDate: "Select Date",
    typeOfJob: "Type of Job",
    paymentMethod: "Payment Method",
    stayProvided: "Stay Provided",
    jobLocation: "Job Location",
    postedDate: "Posted Date",
    signOutModalText: "Are you sure you want to log out?",
    note: "Note",
    stayIncludes: "Stay Includes",
    selectCategory: "Select Category",
    makeEveryTrip: "Make Every Trip a",
    memory:"Memory",
    citylife:"City Life",
    Simplified:"Simplified.",
    discoverYour:"Discover Your",
    perfectStay:"Perfect Stay",
    your:"Your",
    foodguide:"Food Guide",
    

  },
  
  my: {
    title: "အလုပ်အမျိုးအစား",
    name: "အမည်",
    place: "နေရာ",
    highlights: "လည်ပတ်စရာနေစရာများ",
    location: "တည်နေရာ",
    date: "ရက်စွဲ",
    pinkCard: "ဘတ်",
    thai: "ထိုင်းစကား",
    paymentType: "ငွေပေးချေမှုအမျိုးအစား",
    stay: "နေစရာ",
    notes: "မှတ်ချက်",
    adminJobManagement: "အက်ဒမင် အလုပ်စီမံခန့်ခွဲမှု",
    noJobs: "အလုပ်များ မရှိပါ",
    backToDashboard: "ဒက်ရှ်ဘုတ်သို့ ပြန်သွားပါ",
    deleteConfirm: "သေချာပြီး ဖျက်လိုပါသလား?",
    cancel: "မဖျက်တော့ပါ",
    delete: "ဖျက်မည်",
    add: "အသစ်တင်မည်",
    edit: "ပြင်မည်",
    address: "လိပ်စာ",
    monthly: "လစား",
    daily: "နေ့စား",
    addressRequired: "(နေစရာပေးလျှင် ဖြည့်ရန်)",
    images: "ဓာတ်ပုံ",
    rentFee: "စျေးနှုန်း",
    services: "ဝန်ဆောင်မှုများ",
    price: "စျေးနှုန်း",
    nearby: "လည်ပတ်စရာများ",
    amenities: "ဝန်ဆောင်မှုများ",
    nearbyPlaces: "လည်ပတ်စရာများ",
    save: "သိမ်းမည်",
    popular: "အကောင်းဆုံးမီနူးများ",
    adminRating: "အဆင့်ပေးသက်မှတ်ချက်",
    rating: "အဆင့်ပေးသက်မှတ်ချက်",
    duration: "သင်တန်းကာလ",
    coursename: "သင်တန်းအမည်",
    courseprice: "သင်တန်းကြေး",
    centreName: "ကျောင်းအမည်",
    adminJobs: "အလုပ်အကိုင် လမ်းညွှန်",
    adminTravel: "ခရီးသွား လမ်းညွှန်",
    adminCondo: "ကွန်ဒို အခန်း လမ်းညွှန်",
    adminHotels: "ဟိုတယ် လမ်းညွှန်",
    adminDocument: "အထောက်အထား လမ်းညွှန်",
    adminRestaurants: "စားသောက်ဆိုင် လမ်းညွှန်",
    adminCourses: "သင်တန်း လမ်းညွှန်",
    adminGeneral: "အထွေထွေ လမ်းညွှန်",
    jobs: "အလုပ်အကိုင် လမ်းညွှန်",
    travel: "ခရီးသွား လမ်းညွှန်",
    condo: "ကွန်ဒို အခန်း လမ်းညွှန်",
    hotels: "ဟိုတယ် လမ်းညွှန်",
    documents: "အထောက်အထား လမ်းညွှန်",
    restaurants: "စားသောက်ဆိုင် လမ်းညွှန်",
    courses: "သင်တန်း လမ်းညွှန်",
    general: "အထွေထွေ လမ်းညွှန်",
    socialMediaPrompt: "User တိုင်း join ထားသင့်တဲ့ Social Media မျာ",
    goodMorning: "ကောင်းသောနံနက်ခင်းပါ",
    goodAfternoon: "ကောင်းသောနေ့လည်ခင်းပါ",
    goodEvening: "ကောင်းသောညနေခင်းလေးပါ။",
    footerText: "ဘာပဲလိုလို ရာစုကိုသတိရလိုက်ပါ",
    loadingJobs: "အလုပ်များ တင်နေသည်...",
    bhatNeeded: "ဘတ်လိုအပ်သည်",
    posted: "တင်ထားသည့်ရက်စွဲ",
    moreInfo: "အသေးစိတ်သိရှိရန်",
    apply: "လျှောက်ထားရန်",
    applyForJob: "အလုပ်အတွက် လျှောက်ထားရန်",
    phoneNumber: "ဖုန်းနံပါတ်",
    birthday: "မွေးနေ့",
    thaiLanguage: "ထိုင်းဘာသာစကား",
    gender: "ကျား/မ",
    yes: "yes",
    no: "no",
    male: "ကျား",
    female: "မ",
    selectDate: "ရက်စွဲရွေးပါ",
    typeOfJob: "အလုပ်အမျိုးအစား",
    paymentMethod: "ငွေပေးချေမှုနည်းလမ်း",
    stayProvided: "နေစရာပေးထားသည်",
    jobLocation: "အလုပ်နေရာ",
    postedDate: "တင်ထားသည့်ရက်စွဲ",
    signOutModalText:"ထွက်လိုသည်မှာ သေချာပါသလား။",
    note:"မှတ်ချက်",
    stayInclude:"ဝန်ဆောင်မှုများ",
    selectCategory:"အမျိုးအစားကိုရွေးချယ်ပါ။",
    makeEveryTrip:"ပျော်ရွှင်စရာ ကောင်းသော ခရီးများ",
    memory: "ဖန်တီးလိုက်ပါ",
    citylife:"ကွန်ဒိုအခန်းများ",
    Simplified:"ရှာဖွေရန်",
    discoverYour:"ဟိုတယ် အခန်းများ",
    perfectStay:"ရှာဖွေရန်",
    your:"အကောင်းဆုံး စားသောက်ဆိုင်များ",
    foodguide:"ရှာဖွေလိုက်ပါ",
  }
};
  
